services:
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: test_db
      TZ: Asia/Manila
    volumes:
      - mongo:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - MONGO_HOST=mongo
      - PORT=5000
    depends_on:
      - mongo

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "4173:4173"

volumes:
  mongo:
