services:
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_USERNAME: user
      MONGO_INITDB_PASSWORD: password
      MONGO_INITDB_DATABASE: test_db
    volumes:
      - mongo:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - MONGO_HOST=mongo
    depends_on:
      - mongo

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "4173:4173"

volumes:
  mongo:
